coverage:
  precision: 2
  round: up
  range: "60...100"

ignore:
  ## Ignore arg.go as all of those are tested indirectly or as integration
  - "arg.go"
  - "argtype_string.go"
  - "errtype_string.go"
  - "eventtopic_string.go"
