// Code generated by "stringer -type=ErrType"; DO NOT EDIT.

package di

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrServiceNotFound-0]
	_ = x[ErrProviderMissing-1]
	_ = x[ErrProviderNotAFunc-2]
	_ = x[ErrParamProviderGet-3]
	_ = x[ErrProviderToManyReturnValues-4]
	_ = x[ErrProviderArgCountMismatch-5]
	_ = x[ErrProviderArgTypeMismatch-6]
}

const _ErrType_name = "ErrServiceNotFoundErrProviderMissingErrProviderNotAFuncErrParamProviderGetErrProviderToManyReturnValuesErrProviderArgCountMismatchErrProviderArgTypeMismatch"

var _ErrType_index = [...]uint8{0, 18, 36, 55, 74, 103, 130, 156}

func (i ErrType) String() string {
	if i < 0 || i >= ErrType(len(_ErrType_index)-1) {
		return "ErrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrType_name[_ErrType_index[i]:_ErrType_index[i+1]]
}
