// Code generated by "stringer -type=EventTopic -trimprefix=EventTopic -linecomment"; DO NOT EDIT.

package di

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTopicDIReady-0]
}

const _EventTopic_name = "di:ready"

var _EventTopic_index = [...]uint8{0, 8}

func (i EventTopic) String() string {
	if i < 0 || i >= EventTopic(len(_EventTopic_index)-1) {
		return "EventTopic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventTopic_name[_EventTopic_index[i]:_EventTopic_index[i+1]]
}
