// Code generated by "stringer -type=ServiceRef -output=zz_gen_serviceref_string.go -linecomment"; DO NOT EDIT.

package di

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoggerService-1]
}

const _ServiceRef_name = "LoggerService"

var _ServiceRef_index = [...]uint8{0, 13}

func (i ServiceRef) String() string {
	i -= 1
	if i < 0 || i >= ServiceRef(len(_ServiceRef_index)-1) {
		return "ServiceRef(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ServiceRef_name[_ServiceRef_index[i]:_ServiceRef_index[i+1]]
}
