// Code generated by "stringer -type=Level -output=zz_gen_level_string.go"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Warning-0]
	_ = x[Notice-1]
	_ = x[Info-2]
	_ = x[Debug-3]
}

const _Level_name = "WarningNoticeInfoDebug"

var _Level_index = [...]uint8{0, 7, 13, 17, 22}

func (i Level) String() string {
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
