// Code generated by "stringer -type=ServiceRef"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceGoodMorningGreeter-0]
	_ = x[ServiceGoodAfternoonGreeter-1]
	_ = x[ServiceGoodEveningGreeter-2]
}

const _ServiceRef_name = "ServiceGoodMorningGreeterServiceGoodAfternoonGreeterServiceGoodEveningGreeter"

var _ServiceRef_index = [...]uint8{0, 25, 52, 77}

func (i ServiceRef) String() string {
	if i < 0 || i >= ServiceRef(len(_ServiceRef_index)-1) {
		return "ServiceRef(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceRef_name[_ServiceRef_index[i]:_ServiceRef_index[i+1]]
}
